# netlify.toml
[build]
  functions = "netlify/functions"
  publish = "public"

# Configuração das Functions
[functions]
  directory = "netlify/functions"

# Redirecionamentos da API - CORRIGIDOS
[[redirects]]
  from = "/api/workouts/:id"
  to = "/.netlify/functions/get-workout"
  status = 200
  force = true

[[redirects]]
  from = "/api/workouts"
  to = "/.netlify/functions/save-workout"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

# Redirecionamentos das aplicações
[[redirects]]
  from = "/aluno"
  to = "/aluno.html"
  status = 200

[[redirects]]
  from = "/personal"
  to = "/personal.html"
  status = 200

# Fallback para arquivos de dados (permitir acesso direto aos JSONs)
[[redirects]]
  from = "/data/workouts/*"
  to = "/data/workouts/:splat"
  status = 200
  force = false

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para as APIs
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Headers específicos para as Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Cache para arquivos estáticos
[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0"

# Headers para arquivos de dados JSON
[[headers]]
  for = "/data/workouts/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"